<Project>
	<ItemGroup>
    <PackageReference Update="Swashbuckle.AspNetCore" Version="9.0.3"/>
    <PackageReference Update="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Update="Pelican.Mediator" Version="1.1.2" />
    <PackageReference Update="Pigeon.Messaging" Version="2.0.0" />
    <PackageReference Update="Spider.Pipelines" Version="2.0.0" />
    <PackageReference Update="Microsoft.EntityFrameworkCore" Version="9.0.7" />
    <PackageReference Update="Microsoft.EntityFrameworkCore.Relational" Version="9.0.7" />
    <PackageReference Update="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.7" />
    <PackageReference Update="Crabalidator" Version="1.0.1" />
    <PackageReference Update="OctoMap" Version="1.0.0" />
    <PackageReference Update="OctoMap.Analyzers" Version="1.0.0" />
    <PackageReference Update="Sieve" Version="2.5.5" />
    <PackageReference Update="Ulid" Version="1.4.1" />
    <PackageReference Update="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.7"/>
	<PackageReference Update="Asp.Versioning.Mvc" Version="8.1.1" />
	<PackageReference Update="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.1" />
    <PackageReference Update="TurtlePath" Version="1.0.0" />
    <PackageReference Update="TurtlePath.Abstractions" Version="1.0.0" />
    <PackageReference Update="TurtlePath.Analyzers" Version="1.0.0" />
    <PackageReference Update="TurtlePath.Crabalidator" Version="1.0.0" />
    <PackageReference Update="TurtlePath.Domain" Version="1.0.0" />
    <PackageReference Update="TurtlePath.EntityFrameworkCore" Version="1.0.0" />
    <PackageReference Update="TurtlePath.OctoMap" Version="1.0.0" />
    <PackageReference Update="TurtlePath.Sieve" Version="1.0.0" />
  </ItemGroup>

</Project>
